[build]
  base = "commpro"
  command = "npm run build"
  publish = "commpro/build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200