[build]
  command = "npm install && npm run build"
  publish = "build"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 